[[redirects]]
  from = "/api/*"
  to = "http://204.12.229.26:5000/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "X-API-Key, Content-Type" 